import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import CustomQueryClientProvider from '../pages/lib/providers/CustomQueryProvider';
import CustomThemeProvider from '../pages/lib/providers/CustomThemeProvider';

const plusJakartaSans = Roboto({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className}`}>
        <CustomQueryClientProvider>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </CustomQueryClientProvider>
      </body>
    </html>
  );
}
