import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Layout from '../pages/article/ui/Layout/Layout';

const plusJakartaSans = Roboto({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className}`}>
        {children}
        <Layout />
      </body>
    </html>
  );
}
